name: Build when merged at Develop

on:
  push:
    branches:
      - 'develop'
      - 'release/*'

jobs:
  upload:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: develop

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

