name: Build and deploy debug to firebase app distribution

on:
  push:
    branches:
      - 'develop'
      - 'release/*'

jobs:
  upload:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: develop

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

#      - name: Slack Notifications
#        uses: rtCamp/action-slack-notify@master
#        env:
#          SLACK_WEBHOOK: ${{ Secrets.SLACK_CI_WEBHOOK }}
#          SLACK_USERNAME: AppDistribution
#          SLACK_ICON_EMOJI: ':firebase:'
#          SLACK_CHANNEL: android_ci
#          SLACK_TITLE: Staging