name: Build on Pull Requests

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: ktlint
        uses: ScaCap/action-ktlint@1.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
      - name: Slack Notifications
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: Stipop Github bots
          SLACK_ICON_EMOJI: ':android1:'
          SLACK_CHANNEL: android_ci
          SLACK_TITLE: Message
          SLACK_MESSAGE : 'New Pull Request is Arrived.'