name: Build when merged into Master

on:
  push:
    branches:
      - 'master'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: master

      - name: Slack Notifications
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: Stipop Github Bot
          SLACK_ICON_EMOJI: ':android1:'
          SLACK_CHANNEL: android_dev
          SLACK_TITLE: Merged into Master (Release)